GADSPE , ngroup00.gam                response * ngroup00
GADSPE , ngroup01.gam                response * ngroup01
GADSPE , ngroup02.gam                response * ngroup02
GADSPE , ngroup03.gam                response * ngroup03
GADSPE , ngroup04.gam                response * ngroup04
GADSPE , ngroup05.gam                response * ngroup05
GADSPE , ngroup06.gam                response * ngroup06
GADSPE , ngroup07.gam                response * ngroup07
GADSPE , ngroup08.gam                response * ngroup08
GADSPE , ngroup09.gam                response * ngroup09
GADSPE , ngroup10.gam                response * ngroup10
GADSPE , ngroup11.gam                response * ngroup11
GADSPE , ngroup12.gam                response * ngroup12
GADSPE , ngroup13.gam                response * ngroup13
GADSPE , ngroup14.gam                response * ngroup14
GADSPE , ngroup15.gam                response * ngroup15
GADSPE , ngroup16.gam                response * ngroup16
GADSPE , ngroup17.gam                response * ngroup17
GADSPE , ngroup18.gam                response * ngroup18
GADSPE , ngroup19.gam                response * ngroup19
GADSPE , ngroup20.gam                response * ngroup20
GADSPE , ngroup21.gam                response * ngroup21
GADSPE , ngroup22.gam                response * ngroup22
GADSPE , ngroup23.gam                response * ngroup23
GADSPE , ngroup24.gam                response * ngroup24
GADSPE , ngroup25.gam                response * ngroup25
GADSPE , ngroup26.gam                response * ngroup26
GADSPE , ngroup27.gam                response * ngroup27
GADSPE , ngroup28.gam                response * ngroup28
GADSPE , ngroup29.gam                response * ngroup29
GADSPE , ngroup30.gam                response * ngroup30
GADSPE , ngroup31.gam                response * ngroup31
GADSPE , ngroup32.gam                response * ngroup32
GADSPE , ngroup33.gam                response * ngroup33
GADSPE , ngroup34.gam                response * ngroup34
GADSPE , ngroup35.gam                response * ngroup35
GADSPE , ngroup36.gam                response * ngroup36
GADSPE , ngroup37.gam                response * ngroup37
GADSPE , ngroup38.gam                response * ngroup38
GADSPE , ngroup39.gam                response * ngroup39
GADSPE , ngroup40.gam                response * ngroup40
GADSPE , ngroup41.gam                response * ngroup41
GADSPE , ngroup42.gam                response * ngroup42
GADSPE , ngroup43.gam                response * ngroup43
GADSPE , ngroup44.gam                response * ngroup44
GADSPE , ngroup45.gam                response * ngroup45
GADSPE , ngroup46.gam                response * ngroup46
GADSPE , ngroup47.gam                response * ngroup47
GADSPE , ngroup48.gam                response * ngroup48
GADSPE , ngroup49.gam                response * ngroup49
GADSPE , ngroup50.gam                response * ngroup50
GADSPE , ngroup51.gam                response * ngroup51
GADSPE , ngroup52.gam                response * ngroup52
GADSPE , ngroup53.gam                response * ngroup53
GADSPE , ngroup54.gam                response * ngroup54
GADSPE , ngroup55.gam                response * ngroup55
GADSPE , ngroup56.gam                response * ngroup56
GADSPE , ngroup57.gam                response * ngroup57
GADSPE , ngroup58.gam                response * ngroup58
GADSPE , ngroup59.gam                response * ngroup59
GADSPE , ngroup60.gam                response * ngroup60
GADSPE , ngroup61.gam                response * ngroup61
GADSPE , ngroup62.gam                response * ngroup62
GADSPE , ngroup63.gam                response * ngroup63
GADSPE , ngroup64.gam                response * ngroup64
GADSPE , ngroup65.gam                response * ngroup65
GADSPE , ngroup66.gam                response * ngroup66
GADSPE , ngroup67.gam                response * ngroup67
GADSPE , ngroup68.gam                response * ngroup68
GADSPE , ngroup69.gam                response * ngroup69
GADSPE , ngroup70.gam                response * ngroup70
GADSPE , ngroup71.gam                response * ngroup71
GADSPE , ngroup72.gam                response * ngroup72
GADSPE , ngroup73.gam                response * ngroup73
GADSPE , ngroup74.gam                response * ngroup74
GADSPE , ngroup75.gam                response * ngroup75
GADSPE , ngroup76.gam                response * ngroup76
GADSPE , ngroup77.gam                response * ngroup77
GADSPE , ngroup78.gam                response * ngroup78
