function out=window(in,w)
% WINDOW window the columns of a matrix by a function
%   Y=WINDOW(X) windows each column with a hanning window
%      X is an N by M matrix
%
%   Y=WINDOW(X,'name') windows each column with a function
%     generated by 'name'
%
%   Y=WINDOW(X,W) where W a vector N, multiplies each column by W
%
%   Y=WINDOW(X,[]) simply returns X

N=size(in,1);
if (nargin<2)
  w=hanning(N);
elseif (ischar(w))
  eval(sprintf('w=%s(N);',w));
elseif (isvector(w))
  if (size(w,1)~=N)
    w=w.';
  end
elseif (size(w)==[0 0])
  out=in;
  return
elseif (size(w)==[1 1])
  out=in*w;
  return
end
out=in.*w(:,ones(1,size(in,2)),ones(1,size(in,3)));

